#!/usr/bin/env python

import requests

ENDPOINT = 'http://services.otterbots.net/health-check/'


def summarize_response(response):
    return {
        'status_code': response.status_code,
        'reason': response.reason,
    }


def verify_health():
    result = {}
    try:
        response = requests.get(ENDPOINT)
        result['ok'] = response.ok
        result['response'] = summarize_response(response)
    except Exception as e:
        result['ok'] = False
        result['exception'] = e
    return result


def main():
    while True:
        result = verify_health()
        if not result.get('ok', False):
            print 'Non-OK response: %s' % (result,)

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print 'exiting test...'
